<?php
namespace frontend\modules\back\controllers;

use yii\web\Controller;;
use app\models\Categroy;

/**
 * Site controller
 */
class CategoryController extends BaseController
{
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
        $model = new Categroy();
        $list = $model->find()->where(['id'=>1])->asArray()->all();
        return $this->render('list',['list'=>$list]);
    }
}
