<?php
namespace frontend\modules\back\controllers;

use yii\web\Controller;;
use app\models\Categroy;

/**
 * Site controller
 */
class CategoryController extends BaseController
{
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
        $model = new Categroy();
        $list = $model->find()->where(['del'=>0])->asArray()->all();
        $tree = $model->getTree($list);
        return $this->render('list',['list'=>$tree]);
    }
    
    
    public function  actionAdd()
    {
    	$id = \Yii::$app->request->get('id',0);
	    $model = new Categroy();
    	if(\Yii::$app->request->isPost){
    	    $name = \Yii::$app->request->post('name',null);
    	    if(!empty($name)){
    	        $model->name=trim($name);
    	        $model->f_id=empty($id)?0:$id;
    	        $model->sort=empty($id)?1:$id;
    	        $model->level=empty($id)?1:2;
		        if($model->save()){
		            $this->redirect(array('/back/category/index'));
		        }else{
		        	var_dump($model->errors);
		        	exit;
		        }
	        }
	    }
    	$f_info = $model->find()->where(['id'=>$id])->asArray()->one();
        return $this->render('add',['info'=>$f_info]);
    }
    
    public function actionUpdate()
    {
	    $id = \Yii::$app->request->get('id',0);
	    $model = new Categroy();
	    $info = $model->find()->where(['id'=>$id])->asArray()->one();
	    if(\Yii::$app->request->isPost){
		    $name = \Yii::$app->request->post('name',null);
		    if(!empty($name)){
			    $info->name=trim($name);
			    if($info->save()){
				    $this->redirect(array('/back/category/index'));
			    }else{
				    var_dump($info->errors);
				    exit;
			    }
		    }
	    }
	    return $this->render('update',['info'=>$info]);
    }
    
    public function  actionDelete()
    {
	    $id = \Yii::$app->request->get('id',0);
	    $model = new Categroy();
	    $info = $model->find()->where(['id'=>$id])->one();
	    $info_ = $model->find()->where(['f_id'=>$id,'del'=>0])->one();
	    if(!empty($info_)){
		    $this->redirect(array('/back/category/index'));
		    exit;
	    }
	    $info->del = 1;
	    if($info->save()){
		    $this->redirect(array('/back/category/index'));
	    }else{
		    var_dump($model->errors);
		    exit;
	    }
    }
}
