<?php

namespace frontend\modules\back\controllers;

use app\models\Goods;
use app\models\Order;
use app\models\OrderGoods;

class GoodsController extends BaseController
{
	
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	/**
			goods = [
	            name=>商品,price=>1.12 (最低价格),activity_price=>活动价格,activity_time=>活动时间,discount=>折扣,dis_price=>折扣价，
	 *          sku_list=>[column_1=>[''大、红、系列三，number:1000,price:1.12]],   大红系列三  库存1000  价格1.12
	 *
	 * ];
	 */
	
	
	public function actionIndex()
    {
	    $model = new Goods();
	    $page = \Yii::$app->request->get('page',1);
	    $page = $page < 1 ? 1 : $page;
	    $limit = 20;
	    $start = ($page-1)*$limit;
	    $list = $model->find()->offset($start)->limit($limit)->asArray()->all();
	    $prev =$next=1;
	    if ($page > 1) {
		    $prev = $page-1;
	    }
	    if (count($list) == $limit) {
		    $next = $page+1;
	    }
	    return $this->render('index',['list'=>$list,'prev'=>$prev,'next'=>$next]);
    }
    
    public function actionGoodsDetail()
    {
    
    }

}
