<?php

namespace frontend\modules\back\controllers;

use app\models\Address;
use app\models\Member;
use app\models\Order;

class MemberController extends BaseController
{
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
    	$member_model = new Member();
    	$list = $member_model->find()->asArray()->all();
        return $this->render('index',['list'=>$list]);
    }
    
    public function actionOrder()
    {
        $id = \Yii::$app->request->get('id',0);
	    $order_list = [];
        if(!empty($id)){
	        $model = new Order();
	        $order_list = $model->find()->where(['member_id'=>$id])->asArray()->all();
        }
        return $this->render('order_list',['list'=>$order_list]);
    }
    
    
    public function actionAddress()
    {
    	$mid = \Yii::$app->request->get('mid',0);
    	if(empty($mid)){
		    return $this->redirect(array('/back/member/list'));
	    }
    	$model = new Address();
	    $list = $model->find()->where(['member_id'=>$mid])->asArray()->all();
	    return $this->render('address',['list'=>$list]);
    }
    
    public function actionAddAddress()
    {
        
    }
    
    public function actionUpdateAddress()
    {
    
    }
    
}
