<?php

namespace frontend\modules\back\controllers;

use app\models\Order;
use app\models\OrderGoods;

class OrderController extends BaseController
{
	
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
	    $model = new Order();
	    $page = \Yii::$app->request->get('page',1);
	    $page = $page < 1 ? 1 : $page;
	    $limit = 20;
	    $start = ($page-1)*$limit;
	    $list = $model->find()->offset($start)->limit($limit)->asArray()->all();
	    $prev =$next=1;
	    if ($page > 1) {
		    $prev = $page-1;
	    }
	    if (count($list) == $limit) {
		    $next = $page+1;
	    }
        return $this->render('index',['list'=>$list,'prev'=>$prev,'next'=>$next]);
    }
    
    public function actionOrderDetail()
    {
    	$member_id = \Yii::$app->request->get('mid',0);
    	$id =  \Yii::$app->request->get('oid',0);
	    $order_info = [];
	    $goods_list = [];
    	if(!empty($id)){
    		$model = new Order();
    		$goods_m = new OrderGoods();
    		$condition = ['id'=>$id];
    		$o_con = ['order_id'=>$id];
    		if(!empty($member_id)){
			    $condition['member_id'] = $member_id;
			    $o_con['member_id'] = $member_id;
		    }
		    $order_info = $model->find()->where($condition)->asArray()->one();
		    $goods_list = $goods_m->find()->where($o_con)->asArray()->all();
	    }
	    return $this->render('detail',['order_info'=>$order_info,'goods_list'=>$goods_list]);
    }

}
