<?php

namespace frontend\modules\api\controllers;
use yii\validators\Validator;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;



class BaseController extends \yii\web\Controller
{
	public function beforeAction($action)
	{
		$sign = \Yii::$app->request->post('sign','');
		
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
        return $this->render('index');
    }

}
