<?php

namespace frontend\modules\api\controllers;
use app\models\Categroy;


class CategoryController extends BaseController
{
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	
	public function behaviors(){
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter:: className(),
				'actions' => [
					'index'  => [ 'get'],            //只允许get方式访问
				],
			],
		];
	}
	
	
	public function actionIndex()
    {
	    $model = new Categroy();
	    $list = $model->find()->where(['del'=>0])->asArray()->all();
	    $tree = $model->getTree($list);
	    $data = [
	    	'category'=>$tree,
	    	'errno'=>0,
	    	'errmsg'=>"OK",
	    ];
	    return $this->asJson($data);
    }

}
