<?php
namespace frontend\modules\api\controllers;

use yii\web\Controller;;


/**
 * Site controller
 */
class SiteController extends BaseController
{
	public function beforeAction($action)
	{
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function behaviors()
	{
		return parent::behaviors(); // TODO: Change the autogenerated stub
	}
	
	public function actionIndex()
    {
    
    }
}
